#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(set = 0, binding = 0) readonly buffer datainbuf
{
	float Data[];
} inbuf;

layout(set = 0, binding = 1) buffer dataoutbuf
{
	float Data[];
} outbuf;

layout(set = 0, binding = 2) buffer datatertbuf
{
	float Data[];
} tertbuf;

uvec3 dim = gl_NumWorkGroups;
uvec3 pos = gl_WorkGroupID;

void main()
{
//	outbuf.Data[gl_GlobalInvocationID.x] = pow(2, pos.x);
//	tertbuf.Data[gl_GlobalInvocationID.x] = pow(2, pos.x);
	outbuf.Data[gl_GlobalInvocationID.x] = sqrt(pos.x);
	tertbuf.Data[gl_GlobalInvocationID.x] = sqrt(pos.x);
}